# Generated by Django 3.1.6 on 2022-04-11 09:09

import application.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming_Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incoming_category', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['incoming_category'],
            },
        ),
        migrations.CreateModel(
            name='Order_Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_category', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_category'],
            },
        ),
        migrations.CreateModel(
            name='Ordinance_Resolution_Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Outgoing_Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outgoing_category', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['outgoing_category'],
            },
        ),
        migrations.CreateModel(
            name='Outgoing_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=5000)),
                ('remarks', models.CharField(blank=True, default='None', max_length=5000, null=True)),
                ('file', models.FileField(upload_to='outgoing/', validators=[application.validators.validate_file_extension])),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('outgoing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.outgoing_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_issued', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Ordinance_Resolution_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(default='00', max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('remarks', models.CharField(blank=True, default='None', max_length=5000, null=True)),
                ('file', models.FileField(upload_to='order/', validators=[application.validators.validate_file_extension])),
                ('date_approved', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.ordinance_resolution_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_approved', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Order_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(default='00', max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('remarks', models.CharField(blank=True, default='None', max_length=5000, null=True)),
                ('file', models.FileField(upload_to='order/', validators=[application.validators.validate_file_extension])),
                ('date_signed', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.order_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_signed', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Incoming_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_no', models.CharField(blank=True, default='00', max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, default='None', max_length=5000, null=True)),
                ('description', models.CharField(max_length=5000)),
                ('file', models.FileField(upload_to='incoming/', validators=[application.validators.validate_file_extension])),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('incoming_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.incoming_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_received', 'description'],
            },
        ),
    ]
