# Generated by Django 3.1.6 on 2022-04-07 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220308_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['date_received', 'description']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='year',
        ),
        migrations.AddField(
            model_name='document',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='remarks',
            field=models.CharField(blank=True, default='None', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='series_no',
            field=models.CharField(blank=True, default='00', max_length=200, null=True),
        ),
    ]
