# Generated by Django 3.1.6 on 2022-04-07 19:42

import application.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_auto_20220407_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming_Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incoming_category', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['incoming_category'],
            },
        ),
        migrations.CreateModel(
            name='Incoming_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_no', models.CharField(blank=True, default='00', max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, default='None', max_length=5000, null=True)),
                ('description', models.CharField(max_length=5000)),
                ('file', models.FileField(upload_to='upload_document/', validators=[application.validators.validate_file_extension])),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('incoming_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.incoming_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_received', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Outgoing_Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outgoing_category', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['outgoing_category'],
            },
        ),
        migrations.CreateModel(
            name='Outgoing_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=5000)),
                ('remarks', models.CharField(blank=True, default='None', max_length=5000, null=True)),
                ('file', models.FileField(upload_to='upload_document/', validators=[application.validators.validate_file_extension])),
                ('date_signed', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('outgoing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.outgoing_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_signed', 'description'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
