# Generated by Django 3.1.6 on 2022-04-07 20:40

import application.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20220407_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoing_document',
            options={'ordering': ['date_issued', 'description']},
        ),
        migrations.RenameField(
            model_name='outgoing_document',
            old_name='date_signed',
            new_name='date_issued',
        ),
        migrations.AlterField(
            model_name='incoming_document',
            name='file',
            field=models.FileField(upload_to='incoming/', validators=[application.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='outgoing_document',
            name='file',
            field=models.FileField(upload_to='outgoing/', validators=[application.validators.validate_file_extension]),
        ),
    ]
