# Generated by Django 3.1.6 on 2022-04-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_ordinance_resolution_category_ordinance_resolution_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordinance_resolution_category',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='ordinance_resolution_category',
            old_name='ordinance_category',
            new_name='category',
        ),
    ]
