# Generated by Django 3.1.6 on 2022-04-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20220408_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
